#!/usr/bin/env python

import os, sys, pkg_resources
path = os.path.abspath(pkg_resources.resource_filename(__name__, '..'))
sys.path.insert(1, path)

import nucleotides.s3 as s3

src, dst = sys.argv[1:]
s3.fetch_file(src, dst)
