#!/usr/bin/env ruby

require 'inifile'

CREDS = {
  'secret_key' => {env: 'AWS_SECRET_KEY', file: 'aws_secret_access_key'},
  'access_key' => {env: 'AWS_ACCESS_KEY', file: 'aws_access_key_id'}
}

def fetch_credential(name)
  if cred = ENV[CREDS[name][:env]]
    return cred
  end

  cred_file = File.join(ENV['HOME'], '.aws', 'credentials')
  if not File.exists?(cred_file)
    STDERR.puts "No environment variable set or credential file found for: #{name}"
    exit 1
  end

  if cred = IniFile.load(cred_file)['default'][CREDS[name][:file]]
    return cred
  else
    STDERR.puts "No credential file entry found for: #{CREDS[name][:file]}"
    exit 1
  end
end

puts fetch_credential(ARGV.first.strip)
